name: Build Dev Image

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - '.devcontainer/dev/*'
  pull_request:
    branches: [ main ]
    paths:
      - '.devcontainer/dev/*'

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PATRICK_PAT }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: "{{defaultContext}}:.devcontainer/dev"
          push: true
          tags: ghcr.io/patrick-5546/sailbot_ros2_workspace/dev
          builder: ${{ steps.buildx.outputs.name }}
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          cache-from: type=gha, scope=${{ github.workflow }}
          cache-to: type=gha, scope=${{ github.workflow }}
